version: "3.4"

services:
  web:
    image: teta
    build: .
    stdin_open: true
    tty: true
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
      - 3000:3000
    env_file:
      - .envrc
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/teta

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./tmp/volumes/db-data:/docker-entrypoint-initdb.d
