version: "3.4"

services:
  web:
    image: teta
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RAILS_ENV=development
    stdin_open: true
    tty: true
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
      - 3000:3000
    env_file:
      - .envrc
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/

  db:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5435:5432
    volumes:
      - ./volumes/db-data:/docker-entrypoint-initdb.d
